version: "3"
services:
  master:
    image: pkc278/hadoop:latest
    container_name: CentOS_master
    hostname: master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "9000:22"
      - "8080:8080"
    depends_on:
      - slave1
      - slave2
      - mysql
  slave1:
    image: pkc278/hadoop:latest
    container_name: CentOS_slave1
    hostname: slave1
  slave2:
    image: pkc278/hadoop:latest
    container_name: CentOS_slave2
    hostname: slave2
  mysql:
    image: mysql:latest
    container_name: MySQL
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3316:3306"
