version: "3"
services:
  master:
    image: pkc123/hadoop:latest
    container_name: CentOS_master
    hostname: master
    ports:
      - "9870:9870"
      - "50010:22"
    networks:
      hadoop:
        ipv4_address: 172.28.1.1
    depends_on:
      - slave1
      - slave2
  slave1:
    image: pkc123/hadoop:latest
    container_name: CentOS_slave1
    hostname: slave1
    ports:
      - "8088:8088"
    networks:
      hadoop:
        ipv4_address: 172.28.1.2
  slave2:
    image: pkc123/hadoop:latest
    container_name: CentOS_slave2
    hostname: slave2
    networks:
      hadoop:
        ipv4_address: 172.28.1.3
  mysql:
    image: mysql:latest
    container_name: MySQL
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      hadoop:
        ipv4_address: 172.28.1.4
networks:
  hadoop:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
